import {
  ArrowLeft,
  BookOpen,
  Camera,
  ChefHat,
  ChevronRight,
  Clock3,
  Flame,
  Gauge,
  Home,
  Hand,
  Info,
  LoaderCircle,
  Maximize2,
  Minus,
  Pause,
  Play,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Sparkles,
  Star,
  Thermometer,
  Utensils,
  Waves,
  Wifi,
  Wind,
  X,
} from 'lucide-react';
import { assetPath } from '../assetPath';

const icons = {
  back: ArrowLeft,
  book: BookOpen,
  camera: Camera,
  chef: ChefHat,
  chevron: ChevronRight,
  clock: Clock3,
  flame: Flame,
  gauge: Gauge,
  home: Home,
  pointer: Hand,
  info: Info,
  loader: LoaderCircle,
  maximize: Maximize2,
  minus: Minus,
  pause: Pause,
  play: Play,
  plus: Plus,
  retry: RotateCcw,
  search: Search,
  settings: Settings,
  sparkle: Sparkles,
  star: Star,
  temperature: Thermometer,
  utensils: Utensils,
  waves: Waves,
  wifi: Wifi,
  wind: Wind,
  close: X,
};

const sv03Icons = {
  back: assetPath('/icons/sv03/back.svg'),
  chef: assetPath('/icons/sv03/manual.svg'),
  chevron: assetPath('/icons/sv03/chevron.svg'),
  clock: assetPath('/icons/sv03/clock.svg'),
  close: assetPath('/icons/sv03/close.svg'),
  correct: assetPath('/icons/sv03/correct.svg'),
  danger: assetPath('/icons/sv03/danger.svg'),
  edit: assetPath('/icons/sv03/edit.svg'),
  food: assetPath('/icons/sv03/food.svg'),
  chefHat: assetPath('/icons/sv03/chef-hat.svg'),
  info: assetPath('/icons/sv03/info.svg'),
  pause: assetPath('/icons/sv03/pause.svg'),
  play: assetPath('/icons/sv03/play.svg'),
  poultry: assetPath('/icons/sv03/poultry.svg'),
  retry: assetPath('/icons/sv03/retry.svg'),
  search: assetPath('/icons/sv03/search.svg'),
  settings: assetPath('/icons/sv03/settings.svg'),
  temperature: assetPath('/icons/sv03/temperature.svg'),
  utensils: assetPath('/icons/sv03/recipe.svg'),
  waves: assetPath('/icons/sv03/preheat.svg'),
  wifi: assetPath('/icons/sv03/wifi.svg'),
};

export function Icon({ name, size = 24, strokeWidth = 2, className = '' }) {
  if (sv03Icons[name]) {
    return <img aria-hidden="true" className={`sv03-icon ${className}`} src={sv03Icons[name]} width={size} height={size} alt="" />;
  }
  const Component = icons[name] ?? Info;
  return <Component aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} />;
}
